### ISSUE TITLE
使用 CLI运行, -c  命令不能使用 error: unknown option `-c' 

### ISSUE THREAD

**Issue by 136shine** [unStone/i18n-ast#7]
使用该命令 `npx i18n-ast -c i18n-ast.config.js` 运行项目,报错: error: unknown option `-c' 

执行源码,发现配置文件自定义命名,报错: 预期配置文件不存在
查看源码,发现代码中 `const configPath = `${cwdPath}/${programOption.configPath || 'i18n-ast.config.js'}``使用configPath 字段,实际上应该为config

关于是否由于configPath字段原因导致-c 命令行参数报错,没找到依据

  @unStone 希望作者大大帮忙看下,谢谢~

**Comment by unStone** [comment]
非常感谢指出错误，应该是是config而不是configPath，在0.2.7的版本中已经修复了，现在已经部署了，你可以更新一下看看
