### ISSUE TITLE
wordList is null

### ISSUE THREAD

**Issue by caijingfile** [unStone/i18n-ast#9]
源码collectAndWrite.js
缺少对wordList变量的定义，每次扫描都报错。

有个问题请教下：
现在扫描完后，再次扫描就看不到哪些文件拥有汉字了，只有第一次去扫描或者修改或新增中文后能扫描到文件，我怎么修改能每次都扫描到拥有汉字的文件了。

**Comment by unStone** [comment]
> 源码collectAndWrite.js缺少对wordList变量的定义，每次扫描都报错。
不好意思，通知的邮件可能被我忽略了，wordList未定义已经改了，是我写代码不小心。

> 现在扫描完后，再次扫描就看不到哪些文件拥有汉字了，只有第一次去扫描或者修改或新增中文后能扫描到文件，我怎么修改能每次都扫描到拥有汉字的文件了。
在`src/plugin/plugin-i18n-jsx.js`这个文件中是匹配对应的中文，如果已经转换的文件，会转换为intl.get()的方法，在CallExpression这个方法中会被跳过。你可以深入到我这个代码中修改
